language: go

go:
    - 1.1
    - 1.2

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq --no-install-recommends btrfs-tools libdevmapper-dev build-essential aufs-tools

install:
    - go get github.com/dotcloud/docker
    - go get github.com/goraft/raft
    - github.com/gorilla/mux

script: make test
